#!/usr/bin/env python3

from re import split, findall
from subprocess import check_output
from argparse import ArgumentParser, FileType
from random import choice

from modules import hellparser
from modules.fetcher import Fetcher

quitMessage = [
    "Please don't leave, there's more demons to toast!",
    "Let's beat it -- This is turning into a bloodbath!",
    "You're trying to say you like DOS better than me, right?",
    "I wouldn't leave if I were you. DOS is much worse.",
]

with open("version.txt") as f:
    version = f.read()

argParser = ArgumentParser(
    prog="evil-launcher",
    description="The most evil launcher ever conceived",
    epilog=choice(quitMessage),
)
argParser.add_argument("filename", action="store", type=FileType("r"))
argParser.add_argument("--dry-run", action="store_true")
argParser.add_argument("--remove-temp", action="store_true")
argParser.add_argument("-v", "--version", action="store_true")

arguments = argParser.parse_args()


def readArgumentFile(file):
    textfile = file.read()
    file.close()
    return textfile


arguments.filetext = readArgumentFile(arguments.filename)


# Pattern matching magic
def flatten(xss):
    return [x for xs in xss for x in xs]


if arguments.version:
    print(f"Evil v{version}")
    exit()


def main():

    file = arguments.filetext
    cleanFile = hellparser.clean("[]{}", file)
    filePath = hellparser.getFilepath(arguments.filename.name)
    lines = split("\n", file)
    cleanLines = split("\n", cleanFile)

    Fetcher().fetchMissing(
        cleanLines, filePath, dryRun=arguments.dry_run, removeTemp=arguments.remove_temp
    )

    # Comments is a cleaned, flattened list of every comment
    comments = flatten(hellparser.sanitize([], hellparser.getComments(lines)))

    # Clean the strings
    lines = hellparser.flatASS(lines)
    file = "\n".join(lines)

    # Find wad and config file
    wad = findall(r"\[.*\]", file)[0]
    config = findall(r"\{.*\}", file)
    if config:
        config = config[0]

    mods = hellparser.getMods([wad, config] + comments, lines, filePath)
    mods = hellparser.clean("%", mods)

    # Clean from `[]` and `{}`
    wad = hellparser.clean("[]%", wad)

    if config:
        config = hellparser.clean("{}%", config)
        configCommand = f' -config "{filePath}/{config}"'
    else:
        configCommand = ""

    print(f"The hell file is at `{filePath}`")
    print(f"The wad is `./{wad}`")
    print(f"The config file is `./{config}`")
    # print(f"The mods are `{mods}`")

    if mods:
        modCommand = f" -file {mods}"
    else:
        modCommand = ""

    command = f'gzdoom -iwad "{filePath}/{wad}"{configCommand}{modCommand}'

    print(
        f"""The command {"would" if arguments.dry_run else "will"} be run as
        `{command}`
        """
    )
    if not arguments.dry_run:
        check_output(command, shell=True)


main()
